"""add_hypotheses_to_investigations

Revision ID: 0210a2640772
Revises: da64de4c2d3f
Create Date: 2026-09-17 21:23:25.480532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0210a2640772'
down_revision: Union[str, Sequence[str], None] = 'da64de4c2d3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investigations', sa.Column('hypotheses', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investigations', 'hypotheses')
    # ### end Alembic commands ###
