"""add cloudinary fields to evidence

Revision ID: 6a304b85063a
Revises: 3fdce051064c
Create Date: 2026-09-28 00:35:37.478501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a304b85063a'
down_revision: Union[str, Sequence[str], None] = '3fdce051064c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence', sa.Column('cloudinary_public_id', sa.String(length=500), nullable=True))
    op.add_column('evidence', sa.Column('cloudinary_asset_id', sa.String(length=255), nullable=True))
    op.add_column('evidence', sa.Column('cloudinary_resource_type', sa.String(length=50), nullable=True))
    op.add_column('evidence', sa.Column('cloudinary_delivery_type', sa.String(length=50), nullable=True))
    op.alter_column('evidence', 'storage_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evidence', 'storage_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_column('evidence', 'cloudinary_delivery_type')
    op.drop_column('evidence', 'cloudinary_resource_type')
    op.drop_column('evidence', 'cloudinary_asset_id')
    op.drop_column('evidence', 'cloudinary_public_id')
    # ### end Alembic commands ###
