"""add_evidence_fields_to_investigations

Revision ID: da64de4c2d3f
Revises: b70c44078426
Create Date: 2026-09-17 20:48:59.039146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da64de4c2d3f'
down_revision: Union[str, Sequence[str], None] = 'b70c44078426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investigations', sa.Column('supporting_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('investigations', sa.Column('contradicting_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('investigations', sa.Column('missing_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investigations', 'missing_evidence')
    op.drop_column('investigations', 'contradicting_evidence')
    op.drop_column('investigations', 'supporting_evidence')
    # ### end Alembic commands ###
