"""add incident metadata

Revision ID: f2c9733c8b43
Revises: bb1941cac757
Create Date: 2026-07-27 21:46:10.578736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2c9733c8b43'
down_revision: Union[str, Sequence[str], None] = 'bb1941cac757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('severity', sa.String(length=20), nullable=False))
    op.add_column('incidents', sa.Column('environment', sa.String(length=30), nullable=False))
    op.add_column('incidents', sa.Column('service', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'service')
    op.drop_column('incidents', 'environment')
    op.drop_column('incidents', 'severity')
    # ### end Alembic commands ###
